apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image:  022278165950.dkr.ecr.us-east-1.amazonaws.com/webhook:latest
          workingDir: /db
          command: ["alembic", "-c", "/db/alembic.ini", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL