name: Gateway CI/CD

on:
  push:
    branches: [main]
    paths: ["services/gateway/**"]
  pull_request:
    branches: [main]
    paths: ["services/gateway/**"]

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/service-ci.yml
    with:
      service: gateway
    secrets: inherit